language: java
jdk: oraclejdk8

services:
  - postgresql

  before_script:
  - psql -c 'create database hair_salon_test;' -U postgres

# before_script:
#   - psql -c "CREATE DATABASE hair_salon_test;" -U postgres
#   - psql -c "CREATE USER licio WITH PASSWORD '9353';" -U postgres
#   - "rake db:migrate"

